#!/usr/bin/env bash
# This script displays lines containing the "bash" word
# shellcheck disable=SC2009
var=$(ps aux)
while read -r line
do
if [[ $line == *"bash"* ]]
then
echo "$line"
fi
done < "$var"
