#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinately
#With a sleep 2 in between each iteration
#Displays "I am invincible!!!" when receiving a SIGTERM signal
bye() {
	echo "I am invincible!!!"
	exit 0
}
trap bye SIGTERM
while true
do
echo "To infinity and beyond"
sleep 2
done
