#!/usr/bin/bash
#Display "Best School" 10 times, but for 9th iteration add "Hi"
i=1
while [[ $i -le 10 ]]
do
if [ $i == 9 ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
(( i += 1 ))
done
