#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
i=0
while [[ $i -le 12 ]]
do
echo "Hour: "$i
minute=1
while [[ $minute -le 59 ]]
do
echo $minute
(( minute += 1 ))
done
(( i += 1))
done
