#!/usr/bin/env bash
# This script gives information about the school file
fyle="school"
if [[ -e "$fyle" ]]
then
	echo "school file exists"

	if [[ -s "$fyle" ]]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [[ -f "$fyle" ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
