#!/usr/bin/env bash
#Configures an Ubuntu server
cp /etc/hosts /etc/hosts-new
sed -i 's/127.0.0.1	localhost/127.0.0.2	localhost/' /etc/hosts-new
echo "8.8.8.8	facebook.com" >> /etc/hosts-new
cp -f /etc/hosts-new /etc/hosts
